- name: play with functions
  hosts: local
  connection: local
  vars:
    technologies: devops, linux, ansible, shell
    name: "blackpanther"
    gmail: nanonacho@GMAil.com

  # dictionaries to list
    dict:
      technology: DEVSECOPS
      scope: finding-it's-way
  # list to dictionary
    list:
      - key: name
        value: nanonacho
      - key: field
        value: devops 
  
  tasks:
  - name: print hello with undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ name | default('allanki') }}"  #take default name if non specified


  - name: string to list
    ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split(',') }}"

  - name: dictionaries to list
    ansible.builtin.debug:
       msg: "list are: {{ dict | dict2items }}" 

  - name: list to dictionary
    ansible.builtin.debug:
      msg: "dict are {{ list | items2dict }}"

  # pass result to a variable on spot 
  - name: read the yaml file and take it into variable
    ansible.builtin.set_fact:
       student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml}}"   # "{{ lookup('file', 'student.yaml') | from_yaml}}"   is a standard line  passing reults into student_yaml variable

  - name: convert yaml into json
    ansible.builtin.debug:
       msg: "json: {{ student_yaml | to_json }}"
    
  - name: save json to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"
       
  - name: lower to upper
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: upper to lower
    ansible.builtin.debug:
      msg: "{{ gmail| lower }}"




