- name: install packages
  hosts: local
  connection: local
  tasks:
  - name: loop through packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
      enabled: yes
    loop:
     - nginx
     - mysql
     - redis