- name: vars preference
  hosts: local
  connection: local
  become: yes
  # vars:
  #   NAME: this is from play level
  # vars_prompt:
  # - name: NAME
  #   prompt: what is u r NAME?
  #   private: false
  # vars_files:
  # - course.yaml
  tasks:
  - name: testing variable preference
    # vars:
    #   NAME: this is from task level   
    ansible.builtin.debug:
       msg: "Name: {{ NAME }}"

#preference order
# 1)from ->arguments or cli
# 2)from task level
# 3)from vars-file(course.yaml)
# 4)from -> vars_prompt
# 5)from -> from play level
# 6)from -> inventory