- name: variables from args
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: print the course info
    
    ansible.builtin.debug:
      msg: "course name: {{ COURSE }}, duration: {{ DURATION }}, trainer: {{ TRAINER }}"